### ISSUE TITLE
Missing value handling?

### ISSUE THREAD

**Issue by serbinsh** [EnSpec/hytools#10]
Apologies, I have another question.  Because @daryl-yang and I need to use the ArcticDEM for processing, and because ArcticDEM is more coarse than AVIRIS, we are wondering how we can define missing values for Hytools so that it ignores those edge cases (see attached)? 

Again this is caused by using a DEM that isnt of the same resolution of AVIRIS creating some missing data on scene edges (black area on the edge)

![image (15)](https://user-images.githubusercontent.com/3067369/157927848-6ce6005f-7d98-4d2c-8fda-c6f86add4a09.png)

**Comment by adamchlus** [comment]
Hi Shawn, here are some options:
  1.  Set those pixels to the value of the "data ignore value" specified in the ENVI header.
  2. Specify the 'neon_edge" mask as one of the `calc_mask`s in the config file which will exclude a buffer around the edge of the flightline, for example:
` "neon_edge",
            {'radius' : 5
            }`

**Comment by serbinsh** [comment]
Thanks @adamchlus.  @Daryl-YANG is still exploring whether these solutions work, so lets let him get back to us when he has more details

**Comment by adamchlus** [comment]
Fixed with: https://github.com/EnSpec/hytools/pull/13
